export const siteUrl = new URL("https://nexxcloud.org");
export const repositoryUrl = "https://github.com/ShadowSafin/NexxCloud";
export const releasesUrl = `${repositoryUrl}/releases/latest`;

export const siteConfig = {
  name: "NexxCloud",
  title: "NexxCloud | Self-Hosted Cloud Storage for Your Server",
  description:
    "Deploy NexxCloud on your own hardware for private cloud storage with resumable uploads, secure media delivery, Windows apps, Android access, and Docker setup.",
  shortDescription: "Private, self-hosted cloud storage on your own hardware.",
  keywords: [
    "NexxCloud",
    "Nexx Cloud",
    "NexxCloud app",
    "NexxCloud storage",
    "NexxCloud cloud storage",
    "NexxCloud file manager",
    "NexxCloud cloud drive",
    "NexxCloud personal cloud",
    "NexxCloud private cloud",
    "NexxCloud file upload",
    "NexxCloud file download",
    "NexxCloud desktop app",
    "NexxCloud Windows app",
    "NexxCloud Android app",
    "NexxCloud storage client",
    "NexxCloud secure file transfer",
    "self-hosted cloud storage",
    "private cloud storage",
    "personal cloud storage",
    "secure cloud storage",
    "self-hosted file storage",
    "cloud drive",
    "cloud file manager",
    "cloud storage software",
    "private file hosting",
    "secure file transfer",
    "large file transfer",
    "secure upload",
    "secure download",
    "cloud upload",
    "cloud download",
    "Windows cloud storage",
    "Android cloud storage",
    "desktop cloud storage",
    "mobile cloud storage",
    "cross platform cloud",
    "privacy focused storage",
    "Docker cloud storage",
    "Windows cloud server",
    "NAS file storage",
  ],
  locale: "en_US",
  language: "en-US",
};
